name: quality_quest
description: QualityQuest elevates your software's excellence effortlessly.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Cupertino Icons
  cupertino_icons: ^1.0.2


  #freezed_annotation
  freezed_annotation: ^2.4.1

  #json_annotation
  json_annotation: ^4.8.1

  #Animation
  lottie: ^2.6.0

  #device_info_plus
  device_info_plus: ^9.0.3

  #equatable
  equatable: ^2.0.5

  #bloc
  bloc: ^8.1.2

  #flutter_bloc
  flutter_bloc: ^8.1.3

  #flutter_screenUtil
  flutter_screenutil: ^5.9.0

  #data_time
  date_time: ^0.10.0

  #intl
  intl: ^0.18.1

  #hive
  hive: ^2.2.3

  #hive flutter
  hive_flutter: ^1.1.0

  #image picker
  image_picker: ^1.0.4

  #dio
  dio: ^5.3.3


  #local storage
  shared_preferences: ^2.2.2
  http: ^1.1.0
  http_parser: ^4.0.2
  #dart_jsonwebtoken: ^2.12.0
  jwt_decoder: ^2.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  #Flutter Lints
  flutter_lints: ^2.0.0

  #build_runnner
  build_runner: ^2.4.6

  #json_serializable
  json_serializable: ^6.7.1

  #freezed
  freezed: ^2.4.2


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

